/**
 * Precompute the opaque bounding box of each painting, as fractions of its own
 * image. Hover labels are positioned from these rather than from the DOM box,
 * because every asset carries transparent margin and the margins differ.
 */
import sharp from "sharp";
import { readdir, writeFile } from "node:fs/promises";

const dir = "src/assets/objects";
const files = (await readdir(dir)).filter(f => f.endsWith(".png")).sort();
const out = {};

for (const f of files) {
  const { data, info } = await sharp(`${dir}/${f}`).ensureAlpha().raw().toBuffer({ resolveWithObject: true });
  const { width: W, height: H, channels: C } = info;
  let top = H, left = W, right = 0, bottom = 0;
  for (let y = 0; y < H; y++) {
    for (let x = 0; x < W; x++) {
      if (data[(y * W + x) * C + 3] > 24) {
        if (y < top) top = y;
        if (y > bottom) bottom = y;
        if (x < left) left = x;
        if (x > right) right = x;
      }
    }
  }
  const id = f.replace(/\.png$/, "");
  out[id] = {
    top: +(top / H).toFixed(4),
    right: +((right + 1) / W).toFixed(4),
    bottom: +((bottom + 1) / H).toFixed(4),
    left: +(left / W).toFixed(4),
    aspect: +(W / H).toFixed(4),
  };
  console.log(`${id.padEnd(16)} inset L${(out[id].left*100).toFixed(1)}% R${((1-out[id].right)*100).toFixed(1)}% T${(out[id].top*100).toFixed(1)}% B${((1-out[id].bottom)*100).toFixed(1)}%`);
}

const body = `/**
 * Generated by scripts/genbounds.mjs -- do not edit by hand.
 *
 * The opaque bounding box of each painting, as fractions of its own image.
 * Every asset carries transparent margin, and the margins differ per file, so
 * a hover label placed off the DOM box lands a different distance from the
 * artwork for every object. These bounds are what make that gap consistent.
 */

export interface AssetBounds {
  top: number;
  right: number;
  bottom: number;
  left: number;
  /** Intrinsic width / height of the source image. */
  aspect: number;
}

export const bounds: Record<string, AssetBounds> = ${JSON.stringify(out, null, 2)};
`;
await writeFile("src/assets/bounds.ts", body);
console.log("\nwrote src/assets/bounds.ts");
