/**
 * Generated by scripts/genbounds.mjs -- do not edit by hand.
 *
 * The opaque bounding box of each painting, as fractions of its own image.
 * Every asset carries transparent margin, and the margins differ per file, so
 * a hover label placed off the DOM box lands a different distance from the
 * artwork for every object. These bounds are what make that gap consistent.
 */

export interface AssetBounds {
  top: number;
  right: number;
  bottom: number;
  left: number;
  /** Intrinsic width / height of the source image. */
  aspect: number;
}

export const bounds: Record<string, AssetBounds> = {
  "lamp-off": {
    "top": 0.0072,
    "right": 0.9657,
    "bottom": 0.9949,
    "left": 0.03,
    "aspect": 0.238
  },
  "lamp-on": {
    "top": 0.0061,
    "right": 0.97,
    "bottom": 0.9969,
    "left": 0.03,
    "aspect": 0.238
  },
  "path-stones": {
    "top": 0.0596,
    "right": 0.9948,
    "bottom": 0.9551,
    "left": 0.0124,
    "aspect": 1.5
  },
  "toadstool-amber": {
    "top": 0.0501,
    "right": 0.9844,
    "bottom": 0.9661,
    "left": 0.0449,
    "aspect": 0.6667
  },
  "toadstool-blue": {
    "top": 0.071,
    "right": 0.9688,
    "bottom": 0.9512,
    "left": 0.0586,
    "aspect": 0.6667
  },
  "toadstool-pink": {
    "top": 0.0638,
    "right": 0.9629,
    "bottom": 0.946,
    "left": 0.1152,
    "aspect": 0.6667
  },
  "toadstool-red": {
    "top": 0.0397,
    "right": 0.9814,
    "bottom": 0.974,
    "left": 0.0449,
    "aspect": 0.6667
  },
  "wishing-well": {
    "top": 0.0146,
    "right": 1,
    "bottom": 0.9834,
    "left": 0,
    "aspect": 1.0117
  },
  "wishing-well2": {
    "top": 0.0146,
    "right": 1,
    "bottom": 0.9834,
    "left": 0,
    "aspect": 1.0117
  }
};
